import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./styles/react-dual-listbox.css";
import "./styles/globals.css";
import "./styles/overrides.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400","500","700"] });

export const metadata: Metadata = {
  title: "Invisible test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
